# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["core.py"]

doc_url = "https://tcapelle.github.io/resnet_checkpoints/"

git_url = "https://github.com/tcapelle/resnet_checkpoints/tree/master/"

def custom_doc_links(name): return None
