# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = []

# Cell
from fastai2.vision.all import *

# Cell
def _get_gpu_mem(synchronize=True, empty_cache=True):
    "gpu memory utilization"
    return torch.cuda.memory_allocated(), torch.cuda.memory_cached()